# Generated by Django 3.1.2 on 2020-10-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('member_id', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=200)),
                ('line_id', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
            ],
        ),
    ]
