# Generated by Django 3.1.2 on 2020-10-03 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20201003_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='parent_member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        ),
    ]
