# Generated by Django 3.1.2 on 2020-10-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201003_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.CharField(choices=[('Coach', 'Coach'), ('Grand Dealer', 'Grand Dealer'), ('Dealer', 'Dealer'), ('Super VIP Gold', 'Sup Vip'), ('VIP Gold', 'Vip Gold'), ('VIP', 'Vip'), ('ตัวแทนหลัก', 'Level2'), ('ตัวแทนย่อย', 'Level1'), ('Start', 'Start')], default='Start', max_length=20),
        ),
    ]
