# Generated by Django 3.1.2 on 2020-10-03 12:56

from django.db import migrations, models
import members.models
import members.overwritestorage


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='member_images/no-img.jpg', storage=members.overwritestorage.OverwriteStorage(), upload_to=members.models.content_file_name, validators=[members.models.Member.validate_image]),
        ),
    ]
