# Generated by Django 3.1.2 on 2020-10-14 09:44

from django.db import migrations, models
import members.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(default='member_images/no-img.jpg', upload_to=members.models.content_file_name, validators=[members.models.Member.validate_image]),
        ),
    ]
